### PR TITLE
Fix duplicate name in window title

### LINKED ISSUE #335: Title bar has duplicated name.
### Operating System

Linux

### Description of bug

The title bar is inconsistent. It shows PolyMC twice. It also uses - and — within the same line of text, which is inconsistent. The version number is extremely long and seems unnecessary because it could be moved to a menu instead. 

DFF41764-2729-407B-8DE4-C2126E823CB5

### Steps to reproduce

Install PolyMC. Use PolyMC. 

### Suspected cause

This seems to have been carried over from MultiMC. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by jn64**
Fixes #335

## ~~With this PR~~ see latest https://github.com/PolyMC/PolyMC/pull/811#issuecomment-1160001665

- The main window will be named `Instances`
- The application display name will be `PolyMC <version>`

### Note on Qt platform-specific behaviour

On Windows and Linux, Qt appends the display name to all window titles.

Screenshot of main window and Settings window on GNOME, with display name appended to window titles.

On macOS the display name is not appended to window titles.

## Alternative option

The main window could be named simply `PolyMC <version>`.

This will make the main window title consistent across all 3 platforms. Win/Linux will not have it duplicated; see https://github.com/PolyMC/PolyMC/pull/811#discussion_r901052005.

Please let me know if this is preferred and I'll update the PR.

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]
Looks good. Especially paired with #810 should be a good way to deal with this

File: launcher/ui/MainWindow.cpp [hunk 1]
```diff
@@ -857,8 +857,7 @@ class MainWindow::Ui
 
     void retranslateUi(MainWindow *MainWindow)
     {
-        QString winTitle = tr("%1 - Version %2", "Launcher - Version X").arg(BuildConfig.LAUNCHER_DISPLAYNAME, BuildConfig.printableVersionString());
-        MainWindow->setWindowTitle(winTitle);
+        MainWindow->setWindowTitle(tr("Instances"));
```
Comment (kthchew) [inline launcher/ui/MainWindow.cpp]: > Pls feedback from other platforms

Only "Instances" appears on macOS. By the way, this is [documented by Qt](https://doc.qt.io/qt-5/qwidget.html#windowTitle-prop), but not really comprehensively:

> On some desktop platforms (including Windows and Unix), the application name (from [QGuiApplication::applicationDisplayName](https://doc.qt.io/qt-5/qguiapplication.html#applicationDisplayName-prop)) is added at the end of the window title, if set. This is done by the QPA plugin, so it is shown to the user, but isn't part of the windowTitle string.

I think it's worth noting that instances aren't really the only thing in this window. It's PolyMC's main window; it has stuff like news, buttons to settings, etc. that aren't instances (though it is definitely the main thing, so I can also see why this title makes sense).

I'm curious, what does GNOME show if you remove this line (don't set any title)? On macOS the title is "PolyMC" if you do so. (I suppose it doesn't have the version number, but none of the other apps on my computer put the version number in their window title, either, so...)

Comment (jn64) [reply launcher/ui/MainWindow.cpp]: > Only "Instances" appears on macOS

macOS has a global application menu bar so that makes sense. I think e.g. text editors might only show the file path in the window title.

> I'm curious, what does GNOME show if you remove this line (don't set any title)?

I just noticed setWindowTItle on line 825 as well. If you remove both lines 825 and 860, then the main window is titled `PolyMC <version>` on GNOME (i.e. the windowTitle if unset is the applicationDisplayName, and it does not append the display name again). Can you test this on macOS?

Comment (kthchew) [reply launcher/ui/MainWindow.cpp]: It literally shows nothing 😅
Screen Shot 2022-06-18 at 11 24 40 PM

Comment (jn64) [reply launcher/ui/MainWindow.cpp]: I must admit I know nothing about Qt and I'd vote for calling the main window `Instances` so I don't have to figure this out.

Just thinking out loud

- Need platform specific code? Doubtful, there must be a Qt-ism I'm missing
- Could it be to do with the mac-specific unified toolbar? setUnifiedTitleAndToolBarOnMac
- ~~or the retranslation? My locale is en-GB~~ -- probably not

Comment (kthchew) [reply launcher/ui/MainWindow.cpp]: > I'd vote for calling the main window `Instances` so I don't have to figure this out.

Lol, it’s not a very serious issue anyway and pretty much just a nitpick so don’t worry if that’s what you do. I’d say if the first point below doesn’t work then just go with `Instances`

- Does anything special happen if the window title and application display name are exactly the same? Probably not, but maybe if it’s smart it’ll just show it once
- The unified bar is already set to true. Setting it to false just changes the way the color blends with the toolbar
49DD62FB-2FB1-4520-9C82-C159CF01F9B1

Comment (luni3359) [reply launcher/ui/MainWindow.cpp]: I also think that instances is pretty good name for this

Comment (jn64) [reply launcher/ui/MainWindow.cpp]: > maybe if it’s smart it’ll just show it once

It's smart! (on GNOME). Please test this patch:

```patch
diff --git i/launcher/ui/MainWindow.cpp w/launcher/ui/MainWindow.cpp
index 1cc00e33..2e022a6a 100644
--- i/launcher/ui/MainWindow.cpp
+++ w/launcher/ui/MainWindow.cpp
@@ -822,7 +822,7 @@ public:
         }
         MainWindow->resize(800, 600);
         MainWindow->setWindowIcon(APPLICATION->getThemedIcon("logo"));
-        MainWindow->setWindowTitle(BuildConfig.LAUNCHER_DISPLAYNAME);
+        MainWindow->setWindowTitle(APPLICATION->applicationDisplayName());
 #ifndef QT_NO_ACCESSIBILITY
         MainWindow->setAccessibleName(BuildConfig.LAUNCHER_NAME);
 #endif
@@ -857,7 +857,7 @@ public:
 
     void retranslateUi(MainWindow *MainWindow)
     {
-        MainWindow->setWindowTitle(tr("Instances"));
+//        MainWindow->setWindowTitle(tr("Instances"));
         // all the actions
         for(auto * item: all_actions)
         {

```

Not sure if I should use `APPLICATION->applicationDisplayName()` or `QApplication::applicationDisplayName()`.

---

I guess this is the right way to do it (if we want the main window to be unnamed). Can see the difference in the X window properties:


:x: With windowTitle unset:

```
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "PolyMC 1.4.0-fix/window-title"
```

:heavy_check_mark: With windowTitle set to applicationDisplayName:

```
WM_NAME(STRING) = "PolyMC 1.4.0-fix/window-title"
_NET_WM_NAME(UTF8_STRING) = "PolyMC 1.4.0-fix/window-title"
```

:heavy_check_mark: Or with windowTItle set to "Instances":

```
WM_NAME(STRING) = "Instances"
_NET_WM_NAME(UTF8_STRING) = "Instances — PolyMC 1.4.0-fix/window-title"
```

Comment (kthchew) [reply launcher/ui/MainWindow.cpp]: Your patch works on macOS too; the title is "PolyMC 1.4.0-fix/window-title"! Nice!

> Not sure if I should use `APPLICATION->applicationDisplayName()` or `QApplication::applicationDisplayName()`.

I think what you have now is fine, if only because it matches with the use of `APPLICATION` above it

Now whether you want to do this or just stick with "Instances" is up to you, my original intention with my comment was just to provide some food for thought, I never thought it would be this complicated :p

Comment (jn64) [reply launcher/ui/MainWindow.cpp]: Thanks a lot for the help @kthchew. Don't worry I was curious to find out for myself anyway why Qt be the way it do

Well I don't know how decisions are made around here, guess I'll just wait for the PR to be reviewed

**Review by flowln — APPROVED** [review]
I think I'd prefer not having the "Instances" part, and just have it as "PolyMC - ...". Anyway, either one is fine by me. Thanks!

**Comment by jn64** [comment]
Ok, I think this will ruffle less feathers while addressing the original issue only.

To summarise:

- Display name is `PolyMC <version>`
- Main window title is display name (on all platforms)
- Other window titles will have display name appended (on Win/Linux)

screenshot-polymc-fix-window-title-2

**Review by ZekeZDev — APPROVED** [review]
