### PR TITLE
Fix mrpack manual import in languages that don't use dots

### LINKED ISSUE #777: "Add Instance -> Import from Zip" does not show *.mrpack files when the locale is 繁體中文
### Operating System

Linux

### Version of PolyMC

PolyMC 1.3.1

### Description of bug

Similar to #526, but this time *.mrpack files do not come up. :/

### Steps to reproduce

1. Switch the language to 繁體中文
2. Open "Add Instance -> Import from Zip"
3. Switch to any folders containing any *.mrpack files

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Closes #777

I tried going directly with the specified mimetype ([`application/x-modrinth-modpack+zip`](https://docs.modrinth.com/docs/modpacks/format_definition/#storage)), but it didn't work :c

### CODE REVIEW

**Comment by Scrumplex** [comment]
We could also ship our own mime-type definition. I prepared one as per [FreeDesktop spec](https://specifications.freedesktop.org/shared-mime-info-spec/latest/ar01s02.html):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-modrinth-modpack+zip">
    <sub-class-of type="application/zip"/>
    <comment>Modrinth modpack</comment>
    <glob pattern="*.mrpack"/>
  </mime-type>
</mime-info>
```

Though I couldn't find any information on how to ship this properly except for installing it into the system (where I do not know how to do for our bundles). A hint about doing this is here: https://doc.qt.io/qt-5/qmimedatabase.html#details

**Comment by flowln** [comment]
:o seems too much trouble for just this though lol
the spec says that the file extension must be `mrpack` anyways, it won't change with locale from what I understood from the spec. So we just need to be aware of the dot problem and we should be good

**Comment by Scrumplex** [comment]
I wonder how other projects deal with this issue. Are we just using it wrong?

File: launcher/ui/pages/modplatform/ImportPage.cpp [hunk 1]
```diff
@@ -149,7 +149,7 @@ void ImportPage::setUrl(const QString& url)
 void ImportPage::on_modpackBtn_clicked()
 {
     auto filter = QMimeDatabase().mimeTypeForName("application/zip").filterString();
-    filter += ";;" + tr("Modrinth pack (*.mrpack)");
+    filter += ";;" + tr("Modrinth pack (*.mrpack *mrpack)");
```
Comment (Scrumplex) [inline launcher/ui/pages/modplatform/ImportPage.cpp]: Okay I looked at how other applications do this and it seems like they just put the filter outside of the translation:
```suggestion
    filter += ";;" + tr("Modrinth pack") + " (*.mrpack)";
```

I just tested this, and it works (I manually translated the new string and added a local translation to my development installation)

I am going to push a commit here. Feel free to object!

Comment (flowln) [reply launcher/ui/pages/modplatform/ImportPage.cpp]: makes sense :D

**Comment by Scrumplex** [comment]
(updated comments, added an actual translator comment)

**Comment by flowln** [comment]
> (updated comments, added an actual translator comment)

We should probably be using more the Weblate built-in glossary for this kind of stuff

**Comment by Scrumplex** [comment]
> > (updated comments, added an actual translator comment)
> 
> We should probably be using more the Weblate built-in glossary for this kind of stuff

These translator comments (`//:` and `/*: */`) are more for context on what this translation is actually about. Often times you would need to read the code to actually understand what the translation is about. These comments should help avoid that

**Comment by flowln** [comment]
> These translator comments (`//:` and `/*: */`) are more for context on what this translation is actually about. Often times you would need to read the code to actually understand what the translation is about. These comments should help avoid that

Yea, but stuff like "What's an mrpack?" and how it's generally used in a translation context are good info to have in the glossary :)

**Comment by Scrumplex** [comment]
> > These translator comments (`//:` and `/*: */`) are more for context on what this translation is actually about. Often times you would need to read the code to actually understand what the translation is about. These comments should help avoid that
> 
> Yea, but stuff like "What's an mrpack?" and how it's generally used in a translation context are good info to have in the glossary :)

Oh yes. Totally agree. In this case `// mrpack is a modrinth pack` isn't treated as a translator comment, as it lacks the colon symbol (`//:`) to make it one. Qt's i18n tooling actually takes these comments and makes them available in your translation tool of choice.

**Review by Scrumplex — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Review by d-513 — APPROVED** [review]
