### PR TITLE
Prefer stricter modpack formats during import

### LINKED ISSUE #647: when a pack has both a manifest.json and a modrinth.index.json, PolyMC prefers always the manifest.json
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

1.3.0 or higher

### Description of bug

when a pack has both a manifest.json and a modrinth.index.json, PolyMC prefers always the manifest.json

it'd be useful to use the modrinth.index.json here, since some packs use it to make people be able to use their packs on third party launchers (see https://twitter.com/VazkiiMods/status/1528923557488730112?cxt=HHwWgIC9zf_36bcqAAAA for example)

### Steps to reproduce

.

### Suspected cause

.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes #647 

Flame modpacks use "manifest.json" as their only characteristic for
identification. Some modpacks might have other files called
"manifest.json", which is why we should prefer modpack formats that have
a stricter structure.

One case where the launcher will mistake a Modrinth pack for a CF pack: https://modrinth.com/modpack/herodotus
There is a `manifest.json` in `overrides/config/brandon3055/ProjectIntelligence`

### CODE REVIEW

File: launcher/InstanceImportTask.cpp [hunk 1]
```diff
@@ -135,18 +135,21 @@ void InstanceImportTask::processZipPack()
...
     }
 
-    QStringList blacklist = {"instance.cfg", "manifest.json"};
+    QuaZipDir packZipDir(m_packZip.get());
+
+    bool technicFound = packZipDir.exists("/bin/modpack.jar") || packZipDir.exists("/bin/version.json");
+    bool modrinthFound = packZipDir.exists("/modrinth.index.json");
     QString mmcFound = MMCZip::findFolderOfFileInZip(m_packZip.get(), "instance.cfg");
-    bool technicFound = QuaZipDir(m_packZip.get()).exists("/bin/modpack.jar") || QuaZipDir(m_packZip.get()).exists("/bin/version.json");
     QString flameFound = MMCZip::findFolderOfFileInZip(m_packZip.get(), "manifest.json");
```
Comment (flowln) [inline launcher/InstanceImportTask.cpp]: Maybe move the checks, especially the mmc and flame ones, to the `if`statement itself? Seem like a waste searching recursively for those even if it's a technic / modrinth pack :/

Comment (Scrumplex) [reply launcher/InstanceImportTask.cpp]: Oh, wait. Now I wonder if this code is causing the freeze of a few seconds when importing zips.

**Review by flowln — APPROVED** [review]
nice :D

**Review by txtsd — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]
