### PR TITLE
Use MC versions list instead of ad-hoc logic to filter by major version in the mod downloader

### LINKED ISSUE #995: mod download version match is buggy/non-intuitive
### Operating System

Linux

### Version of PolyMC

PolyMC 1.4.1

### Description of bug

on an 1.19 instance, when i search modrinth for mods, i do not get matches for 1.19.1 even when selecting to filter for major version.  I do not know if this is a bug or intended behaviour.  if the latter, then clarification is needed.

### Steps to reproduce

on 1.19 instance, click download mods, filter for major version, search for lithium the most recent version for 1.19.1 (0.8.3) is not among the matches.

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Fixes #995

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]

File: launcher/ui/widgets/ModFilterWidget.cpp [hunk 1]
```diff
@@ -16,6 +18,24 @@ ModFilterWidget::ModFilterWidget(Version def, QWidget* parent)
...
+        connect(task.get(), &Task::failed, [this]{
+            ui->majorVersionButton->setText(tr("Major version match (failed to get version index)"));
+            disableVersionButton(VersionButtonID::Major);
+        });
+        connect(task.get(), &Task::finished, &load_version_list_loop, &QEventLoop::quit);
+
+        if (!task->isRunning())
+            task->start();
+
+        load_version_list_loop.exec();
```
Comment (LennyMcLennington) [inline launcher/ui/widgets/ModFilterWidget.cpp]: What's the event loop needed for? (Why not have a slot?)

Comment (flowln) [reply launcher/ui/widgets/ModFilterWidget.cpp]: To wait for the version list to load before showing the widget, so that if an error occurs we can disable the `majorVersionButton` before showing it to the user, and if the list loaded successfully, the filter option works at all.

Comment (LennyMcLennington) [reply launcher/ui/widgets/ModFilterWidget.cpp]: > To wait for the version list to load before showing the widget, so that if an error occurs we can disable the `majorVersionButton` before showing it to the user, and if the list loaded successfully, the filter option works at all.

Why can't this be done by just hiding the widget first and connecting to a slot that unhides it? Having a local QEventLoop, especially in a class constructor, feels like the wrong approach.

Comment (flowln) [reply launcher/ui/widgets/ModFilterWidget.cpp]: hiding the widget and only showing it later seems more like a bug. ideally, when the dialog opens, you'd have everything loaded too, lazy-loading this kind of stuff doesn't look right.

regarding having it in the class constructor, even though it shouldn't cause any issues, we could just have it be done in a factory method, the main point is to have it available by the time the user sees the UI.

Comment (LennyMcLennington) [reply launcher/ui/widgets/ModFilterWidget.cpp]: So is there also no way to show the window with a slot after it's loaded?

Comment (flowln) [reply launcher/ui/widgets/ModFilterWidget.cpp]: there can be a way to do that, but why? i don't see much problem in using a QEventLoop here, it's simpler than doing whatever you'd need to to delay the window's show() until the list is loaded, and from testing, the delay caused by it isn't even noticeable for me..

Comment (LennyMcLennington) [reply launcher/ui/widgets/ModFilterWidget.cpp]: I don't really know whether it's a bad approach, it's just my gut feeling. Totally possible that my feeling is completely wrong. If you're sure this is fine and there's no caveats to using a local event loop here that would cause any problem then I'll approve it.

Comment (flowln) [reply launcher/ui/widgets/ModFilterWidget.cpp]: i've moved the thing to a factory method, and added a QTimer on it to be extra extra sure. this should make it somewhat similar to what we do on other parts of the code base, so shouldn't be any problems there.

**Review by cozyGalvinism — APPROVED** [review]

**Comment by DioEgizio** [comment]
2 approvals 👀

**Comment by RaptaG** [comment]
So close to 1.4.2 🎉

**Comment by Scrumplex** [comment]
I am not able to backport this to 1.4.2, as it relies on some changes from prior PRs targeting 5.0
