### PR TITLE
Actually check if a mod loader is selected when creating an instance

### LINKED ISSUE #447: Crash when switching mod loader and back in New Instance dialog
### Operating System

Windows

### Description of bug

In the New Instance dialog, if you change the mod loader to anything supported by the selected Minecraft version then back to None, PolyMC crashes trying to create the instance.

### Steps to reproduce

* Open PolyMC
* Click New Instance on the main toolbar
* Change Mod Loader near the bottom right to Forge
* Change the Mod Loader back to None
* Click OK

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #453: Unable to remove modloader if created using the new initial modloader selector
### Operating System

Linux

### Description of bug

I am unable to remove modloader if created using the new initial modloader selector. I have not tested this with other modloaders then quilt. I am able to delete it if i first downgrade the modloader then delete it.

### Steps to reproduce

1. Make a new instance using the new modloader selector
2. Attempt to delete the modloader

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes #447 
Closes #453

### CODE REVIEW

**Comment by Scrumplex** [comment]
CC @kthchew

File: launcher/InstanceCreationTask.cpp [hunk 1]
```diff
@@ -31,7 +31,7 @@ void InstanceCreationTask::executeTask()
         components->buildingFromScratch();
         components->setComponentVersion("net.minecraft", m_version->descriptor(), true);
         if(m_usingLoader)
-            components->setComponentVersion(m_loader, m_loaderVersion->descriptor(), true);
+            components->setComponentVersion(m_loader, m_loaderVersion->descriptor());
```
Comment (kthchew) [inline launcher/InstanceCreationTask.cpp:34]: Yeah, I wasn't sure what that did. The dangers of copying and pasting, I suppose lol

**Review by kthchew — APPROVED** [review]

File: launcher/InstanceCreationTask.cpp (hunk 1 above)
Comment (Scrumplex) [reply launcher/InstanceCreationTask.cpp:34]: Yeah no problem. We didn't notice in the initial review either :D

**Review by txtsd — APPROVED** [review]

**Review by ZekeZDev — APPROVED** [review]

**Review by d-513 — APPROVED** [review]
