### PR TITLE
Decode process lines as UTF-8

### LINKED ISSUE #806: Mangled UTF-8 text when displaying logs
### Operating System

Windows

### Version of PolyMC

PolyMC 1.3.2

### Description of bug

Certain log messages are corrupted.

### Steps to reproduce

View a Minecraft log with special characters in the output.

Expected (in Notepad++):
image

Actual (in PolyMC):
image

### Suspected cause

The log viewer does not correctly parse UTF-8 characters when on Windows. Instead, it uses the default Windows codepage which causes corruption. On Linux it correctly uses UTF-8.

I tracked down the logging function to this line: https://github.com/PolyMC/PolyMC/blob/03e454b71d83aebbb534c5734ccd9093842da28c/launcher/LoggedProcess.cpp#L25

I plan to try to set up a dev environment and submit a PR when I get the chance in a few days unless somebody else does it first.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by magneticflux-**
Closes #806

@huangsijun17 can you test this fix? You filed a MultiMC issue ~2.5 years ago so I figured you'd like to know this is being worked on 😆.

### CODE REVIEW

**Comment by magneticflux-** [comment]
Special characters used by DashLoader work:
image

Emoji used by Krypton work:
image

UTF-8 test characters work:
image

It should look like `UTF-8 TEST: κόσμε ࠀ 𐀀`, but the font I'm using (FiraCode NF) doesn't support those 3- and 4-byte characters. They _are_ printed verbatim however and you can copy-paste them into a web browser that uses something more compatible like Roboto.

**Comment by huangsijun17** [comment]
> Closes #806
> 
> @huangsijun17 can you test this fix? You filed a MultiMC issue ~2.5 years ago so I figured you'd like to know this is being worked on 😆.

image
This bug still exists. Please note that I added the java startup parameter`-Dfile.encoding=UTF-8`.

**Comment by magneticflux-** [comment]
@huangsijun17 I don't understand Chinese text, so could you provide pairs of "correct" and "garbled" strings for me to compare and copy/paste when debugging?

You can find portable binaries with this PR in the action's artifacts: https://github.com/PolyMC/PolyMC/actions/runs/2729241234

**Comment by magneticflux-** [comment]
I ran through this test suite: https://pages.ucsd.edu/~dkjordan/chin/unitestuni.html

The Egyptian hieroglyphs were printed as tofu squares in Minecraft and empty squares in the log.
The final "extremely rare Chinese character" was printed as tofu in Minecraft but correctly in the log.
All other characters printed correctly in both Minecraft _and_ the new Unicode log.

(Minecraft appears to dim characters that are above a certain height to prevent obscuring the chat)

image

**Comment by huangsijun17** [comment]
> I ran through this test suite: https://pages.ucsd.edu/~dkjordan/chin/unitestuni.html
> 
> The Egyptian hieroglyphs were printed as tofu squares in Minecraft and empty squares in the log. The final "extremely rare Chinese character" was printed as tofu in Minecraft but correctly in the log. All other characters printed correctly in both Minecraft _and_ the new Unicode log.
> 
> (Minecraft appears to dim characters that are above a certain height to prevent obscuring the chat)
> 
> image

added the java startup parameter`-Dfile.encoding=UTF-8`?
If an ASCII encoding is used under Windows, the Chinese display of some MODs will be abnormal. UTF-8 is required for compulsory.

**Comment by magneticflux-** [comment]
I used these flags, which include `UTF-8` encoding:
```
-Dfile.encoding=UTF-8 -server -XX:+UnlockExperimentalVMOptions -XX:+UseStringDeduplication -XX:+UseZGC -XX:-ZUncommit -XX:ZUncommitDelay=300 -XX:ZCollectionInterval=5 -XX:ZAllocationSpikeTolerance=2.0 -XX:+ExitOnOutOfMemoryError -XX:+AlwaysPreTouch -XX:-DontCompileHugeMethods -XX:-ClipInlining -XX:+TrustFinalNonStaticFields -XX:+UseFastUnorderedTimeStamps -XX:+UseNewLongLShift -XX:+UseVectorCmov -XX:+UseXmmI2D -XX:+UseXmmI2F -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem
```

File: launcher/LoggedProcess.cpp [hunk 1]
```diff
@@ -59,14 +59,18 @@ LoggedProcess::~LoggedProcess()
     }
 }
 
-QStringList reprocess(const QByteArray & data, QString & leftover)
+QStringList reprocess(const QByteArray& data, QByteArray& leftover)
 {
-    QString str = leftover + QString::fromLocal8Bit(data);
```
Comment (flowln) [inline launcher/LoggedProcess.cpp:64]: Maybe i'm missing something really obvious, but why can't you just use `QString::fromUtf8(data)` here? o.O

Comment (magneticflux-) [reply launcher/LoggedProcess.cpp:64]: I want to keep the data as a byte array until we definitely can parse it as UTF-8. I was concerned `leftover` might contain invalid fragments of UTF-8 if the process's std out was flushed mid-line, so I split on the `\n` byte and any bytes after that are saved for the next batch of data.

Comment (magneticflux-) [reply launcher/LoggedProcess.cpp:64]: From the docs of `QString::fromUtf8`:
> UTF-8 is a Unicode codec and can represent all characters in a Unicode string like [QString](https://doc.qt.io/qt-6/qstring.html). However, invalid sequences are possible with UTF-8 and, if any such are found, they will be replaced with one or more "replacement characters", or suppressed. These include non-Unicode sequences, non-characters, overlong sequences or surrogate codepoints encoded into UTF-8.

That replacement would be bad if a sequence got chopped in half. We "protect" the sequence by putting it in `leftover` until a newline occurs.

Comment (flowln) [reply launcher/LoggedProcess.cpp:64]: I see... But then, to avoid having to deal with that weird `QByteArray` interface, which clogs up the code a bit, couldn't we perhaps create a `QString` based on the `QByteArray` and use its interface as we were doing before? Or maybe use something like [`QTextDecoder`](https://doc.qt.io/qt-5/qtextdecoder.html) to avoid having to deal with that leftover at all.

I just would like to get rid of all that `truncate` `remove_if` `transform` stuff if possible, it looks kinda convoluted and i feel like it will come bite us later xD

Comment (magneticflux-) [reply launcher/LoggedProcess.cpp:64]: `QTextDecoder` looks like it does exactly what I'm doing here manually, so I'll migrate to just using that!

> If not all characters are used (e.g. if only part of a multi-byte encoding is at the end of the characters), the decoder remembers enough state to continue with the next call to this function.

**Comment by magneticflux-** [comment]
Input test text:
```
Ā Á Ă Àā á ă àǕ Ǘ Ǚ Ǜǖ ǘ ǚ ǜ Ĉ ĉ Ĝ ĝ Ĥ ĥĴ ĵ Ŝ ŝ Ŭ ŭЯ не говорю по-русски.Μῆνιν ἄειδε θεὰ Πηληϊάδεω Ἀχιλῆος. אני לא לומד עברית𓂝𓃀𓅡𓄿𓌂 𓋴𓅓𓏏𓇏𓇌𓀀我们刚才从图书馆来了。我們剛才從圖書館來了。𦮙
```

Output in log:
```
Ā Á Ă Àā á ă àǕ Ǘ Ǚ Ǜǖ ǘ ǚ ǜ Ĉ ĉ Ĝ ĝ Ĥ ĥĴ ĵ Ŝ ŝ Ŭ ŭЯ не говорю по-русски.Μῆνιν ἄειδε θεὰ Πηληϊάδεω Ἀχιλῆος. אני לא לומד עברית𓂝𓃀𓅡𓄿𓌂 𓋴𓅓𓏏𓇏𓇌𓀀我们刚才从图书馆来了。我們剛才從圖書館來了。𦮙
```
Output in Minecraft:
image

**Review by flowln — APPROVED** [review]
looks tidy! thank u!

**Review by Scrumplex — APPROVED** [review]
I wonder how Qt 6 handles this. `QTextDecoder` is only available using 5Compat. I know that Qt 6 has moved many things to support UTF-8 by default, so maybe in the future it will get easier to handle this

**Comment by Scrumplex** [comment]
Okay, looks like eventually we will have to use [`QStringDecoder`](https://doc.qt.io/qt-6/qstringdecoder.html) for Qt 6.

**Comment by huangsijun17** [comment]
I tested it and started it with parameters. The Chinese in the real-time log is normal, but there is a problem with the log without parameters.

image

**Comment by magneticflux-** [comment]
@huangsijun17 Can you open up `cmd.exe`, run the `chcp` (change/print codepage) command, and share the output?

**Comment by huangsijun17** [comment]
> @huangsijun17 Can you open up `cmd.exe`, run the `chcp` (change/print codepage) command, and share the output?

image

**Comment by magneticflux-** [comment]
Aha, you're using an East Asian multi-byte encoding by default which is _incompatible_ with Unicode.
What does your "Region" page in the control panel look like? (including the popup from "Change system locale")
image

**Comment by huangsijun17** [comment]
> 

image

Simplified Chinese

**Comment by magneticflux-** [comment]
I believe my tests were working because I opted-in to UTF-8 support in Windows some time ago (the "Beta" checkbox).

3c4b45c9e76db3373baccefda59bae01c460df28 now uses whatever C locale is set, which might fix alternate multi-byte encodings like Windows-936.

@huangsijun17 Can you test the build from 3c4b45c9e76db3373baccefda59bae01c460df28 (when it's finished building) with and without setting the `-Dfile.encoding=UTF-8` parameter?

**Comment by huangsijun17** [comment]
> I believe my tests were working because I opted-in to UTF-8 support in Windows some time ago (the "Beta" checkbox).
> 
> [3c4b45c](https://github.com/PolyMC/PolyMC/commit/3c4b45c9e76db3373baccefda59bae01c460df28) now uses whatever C locale is set, which might fix alternate multi-byte encodings like Windows-936.
> 
> @huangsijun17 Can you test the build from [3c4b45c](https://github.com/PolyMC/PolyMC/commit/3c4b45c9e76db3373baccefda59bae01c460df28) (when it's finished building) with and without setting the `-Dfile.encoding=UTF-8` parameter?

image
Wrong with parameters.

**Comment by magneticflux-** [comment]
But is it right _without_ parameters now?

**Comment by huangsijun17** [comment]
> But is it right _without_ parameters now?

Right!

**Review by timoreo22 — APPROVED** [review]
Looks all fine then

**Comment by huangsijun17** [comment]
> Looks all fine then

But it has no effect.

**Comment by huangsijun17** [comment]
I tried using a hex editor to view the UTF-8 encoded log file that was generated with the parameters and found nothing in the file header.
File header identification details:
https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding

**Comment by magneticflux-** [comment]
Yes, that's the issue with getting data from a random process's output stream: there's no way to know the encoding from looking at the bytes. I think using the system locale for encoding is a good default that doesn't cause issues unless you set the encoding of Java to something different.

**Comment by magneticflux-** [comment]
If for some reason you need to run Java in UTF-8 mode instead of your system locale, I believe checking the "Beta: Use Unicode UTF-8 for worldwide language support" box adjusts your system text encoding to UTF-8 by default while keeping the language settings the same.
image

> If you check this option, Windows will use codepage 65001 (Unicode UTF-8) instead of the local codepage like 1252 (Western Latin1) for all plain text files. The advantage is that text files created in e.g. Russian locale can also be read in other locale like Western or Central Europe. The downside is that ANSI-Only programs (most older programs) will show garbage instead of accented characters.

https://stackoverflow.com/a/68066008/9073728

**Comment by magneticflux-** [comment]
In the future (in a separate PR), I don't think it would be terribly difficult to add a Boolean config to force Unicode decoding for those that wish to opt-in. I don't think adding a full custom locale selector would be very useful though.
