### PR TITLE
Fix some Modrinth `mrpack` import issues

### LINKED ISSUE #766: mrpacks with more than one download url in the array don't import correctly
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

PolyMC 1.3.1

### Description of bug

.

### Steps to reproduce

.

### Suspected cause

.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Closes #766 (but CC @DioEgizio test this to be sure, please :p)

Actually, most modpacks weren't working because we were considering the `env` field to be required, but it's optional x.x

The download array is now properly parsed as well, though trying to use the secondary downloads in case the first fails is :pofat: tech :tm:, since we don't **yet** have the proper task mechanisms to do it right (those are being worked on ;) )

This removes the whitelisted hosts check, since people didn't like it and it was causing some issues trying to integrate with multiple download urls anyways
 
 Lastly, this fixes an issue where client overrides where not taken into consideration when importing `mrpack`s!

### CODE REVIEW

**Comment by DioEgizio** [comment]
seems to work now!

File: launcher/InstanceImportTask.cpp [hunk 1]
```diff
@@ -735,13 +740,24 @@ void InstanceImportTask::processModrinth()
...
+        qDebug() << "Will try to download" << file.downloads.front() << "to" << path;
+        auto dl = Net::Download::makeFile(file.downloads.front(), path);
         dl->addValidator(new Net::ChecksumValidator(file.hashAlgorithm, file.hash));
         m_filesNetJob->addNetAction(dl);
+
+        if (file.downloads.size() > 1) {
+            // FIXME: This really needs to be put into a ConcurrentTask of
+            // MultipleOptionsTask's , once those exist :)
+            connect(dl.get(), &NetAction::failed, [this, &file, path, dl]{
+                auto dl = Net::Download::makeFile(file.downloads.dequeue(), path);
```
Comment (Scrumplex) [inline launcher/InstanceImportTask.cpp:755]: won't this use the same URL as before. We haven't dequeued it before.

File: launcher/InstanceImportTask.cpp [hunk 2]
```diff
@@ -735,13 +740,24 @@ void InstanceImportTask::processModrinth()
...
 
     m_filesNetJob = new NetJob(tr("Mod download"), APPLICATION->network());
-    for (auto &file : files)
+    for (auto file : files)
     {
         auto path = FS::PathCombine(m_stagingPath, ".minecraft", file.path);
-        qDebug() << "Will download" << file.download << "to" << path;
-        auto dl = Net::Download::makeFile(file.download, path);
+        qDebug() << "Will try to download" << file.downloads.front() << "to" << path;
+        auto dl = Net::Download::makeFile(file.downloads.front(), path);
```
Comment (Scrumplex) [inline launcher/InstanceImportTask.cpp]: ?
```suggestion
        auto dl = Net::Download::makeFile(file.downloads.dequeue(), path);
```

File: launcher/InstanceImportTask.cpp (hunk 1 above)
Comment (flowln) [reply launcher/InstanceImportTask.cpp:755]: oops T-T

File: launcher/InstanceImportTask.cpp [hunk 3]
```diff
@@ -735,13 +740,24 @@ void InstanceImportTask::processModrinth()
...
     {
         auto path = FS::PathCombine(m_stagingPath, ".minecraft", file.path);
-        qDebug() << "Will download" << file.download << "to" << path;
-        auto dl = Net::Download::makeFile(file.download, path);
+        qDebug() << "Will try to download" << file.downloads.front() << "to" << path;
+        auto dl = Net::Download::makeFile(file.downloads.dequeue(), path);
         dl->addValidator(new Net::ChecksumValidator(file.hashAlgorithm, file.hash));
         m_filesNetJob->addNetAction(dl);
+
+        if (file.downloads.size() > 1) {
```
Comment (Scrumplex) [inline launcher/InstanceImportTask.cpp]: Now this probably also needs to be changed :D
```suggestion
        if (file.downloads.size() > 0) {
```

**Review by d-513 — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]
