### PR TITLE
Fix skipping file in mod version parsing

### LINKED ISSUE #332: the mod downloader doesn't find some mods for ? reasons on devbuilds
### Operating System

Windows, macOS, Linux, Other

### Description of bug

immagine
https://modrinth.com/mod/lithium/version/mc1.16.5-0.6.6
pretty frequent for some reason
### Steps to reproduce

auto-explaining

### Suspected cause

#296 maybe????

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Closes #332. This was introduced in #296 by me! Sorry!

### CODE REVIEW

File: launcher/modplatform/modrinth/ModrinthPackIndex.cpp [hunk 1]
```diff
@@ -55,7 +55,8 @@ void Modrinth::loadIndexedPackVersions(Modrinth::IndexedPack & pack, QJsonArray
         // Find correct file (needed in cases where one version may have multiple files)
         // Will default to the last one if there's no primary (though I think Modrinth requires that
         // at least one file is primary, idk)
-        while (i < files.count()){
+        // NOTE: files.count() is 1-indexed, so we need to subtract 1 to become 0-indexed
```
Comment (luni3359) [inline launcher/modplatform/modrinth/ModrinthPackIndex.cpp:58]: It's not that the count is 1-indexed, it's just that it's the actual count. So if one element exists, count is one but it's on index 0.

**Comment by DioEgizio** [comment]
yeah this fixes the bug

File: launcher/modplatform/modrinth/ModrinthPackIndex.cpp [hunk 2]
```diff
@@ -55,7 +55,8 @@ void Modrinth::loadIndexedPackVersions(Modrinth::IndexedPack & pack, QJsonArray
...
+        while (i < files.count() - 1){
```
Comment (Scrumplex) [inline launcher/modplatform/modrinth/ModrinthPackIndex.cpp:59]: I guess this is fine for now. It us kinda ugly though

**Review by Scrumplex — APPROVED** [review]

File: launcher/modplatform/modrinth/ModrinthPackIndex.cpp (hunk 1 above)
Comment (flowln) [reply launcher/modplatform/modrinth/ModrinthPackIndex.cpp:58]: Yes, but it's easier for someone who is just reading the code, to understand it as a way of conversion basis of index of two related quantities, rather than comparing two different things with two different basis, and having to convert between them, at least in my option :^)

File: launcher/modplatform/modrinth/ModrinthPackIndex.cpp (hunk 2 above)
Comment (flowln) [reply launcher/modplatform/modrinth/ModrinthPackIndex.cpp:59]: I agree. But it's easier to think about than the previous `files.count() > 1 &&` before that other PR

**Review by txtsd — APPROVED** [review]

**Review by cozyGalvinism — APPROVED** [review]
